name: release-kubectl-plugin
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Desired release version tag (e.g. v1.1.0-rc.1).'
        required: true
jobs:
  release-kubectl-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-tags: 'true'
      - name: Show tag
        run: git show-ref --head --dereference | grep "$(git rev-parse HEAD)"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: 'goreleaser'
          version: latest
          args: release --clean
          workdir: 'kubectl-plugin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.46
